{% set name = "msodbc" %}
{% set version = "18.3.3.1" %}
{% set major = version.split('.')[0] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://packages.microsoft.com/debian/12/prod/pool/main/m/{{ name }}sql{{ major }}/{{ name }}sql{{ major }}_{{ version }}-1_arm64.deb
  sha256: 37e692b1517f1229042c743d0f2a7191e0dcb956bbc3785a895aaa6dc328467e

build:
  skip: true  # [not linux]
  number: 0

requirements:
  build:
  - libcurl

test:
  commands:
    - test -f $PREFIX/lib/libmsodbcsql-{{ major }}.so

about:
  home: https://learn.microsoft.com/en-us/sql/connect/odbc
  license_file: LICENSE.txt
  summary: Microsoft ODBC driver for SQL Server

extra:
  recipe-maintainers:
    - IsabelParedes
